### ISSUE TITLE
Crash Log

### ISSUE THREAD

**Issue by ardissaps** [bunten2005/tooltiptweaks-mod#3] opened 2022-07-09 04:13 UTC
https://paste.atlauncher.com/view/76f6d881-79f1-4db6-9c22-dd042f390473

**Comment by lunarbunten** [comment] 2022-07-15 06:19
Duplicate of #2 

This has been fixed and the changes will be present in the next update

**Closed as completed by lunarbunten** 2022-07-15 06:19 UTC

**Comment by ardissaps** [comment] 2022-07-15 09:29
Thanks, I hope the fix also contain 1.18.2 :p
